apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: "dev"

  # 데이터베이스 설정
  SPRING_DATASOURCE_URL: "jdbc:mariadb://chaing-db.cxm2i02o0y36.ap-northeast-2.rds.amazonaws.com:3306/chaing?sslMode=trust&trustServerCertificate=true"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.mariadb.jdbc.Driver"

  # Redis 설정
#  SPRING_DATA_REDIS_HOST: "221.151.189.232"
#  SPRING_DATA_REDIS_PORT: "7006"

  # 메일 및 앱 설정
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  APP_MAIL_FROM: "rlatjddms030@gmail.com"
  APP_MAIL_FROM_NAME: "CHAIN-G"
  APP_URL_LOGIN: "https://www.naver.com/"

  # MinIO 설정
  MINIO_ENDPOINT: "http://minio-service:7003"
  MINIO_ACCESS_KEY: "minioadmin"