apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-secret
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: backend-secret
        property: SPRING_DATASOURCE_PASSWORD
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteRef:
        key: backend-secret
        property: SPRING_DATA_REDIS_PASSWORD
    - secretKey: SPRING_MAIL_PASSWORD
      remoteRef:
        key: backend-secret
        property: SPRING_MAIL_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: backend-secret
        property: JWT_SECRET
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: backend-secret
        property: MINIO_SECRET_KEY