apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 479699168320.dkr.ecr.ap-northeast-2.amazonaws.com/chaing-frontend:53
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10