apiVersion: v1
kind: Service
metadata:
  name: minio-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:479699168320:certificate/239295f6-4dee-4129-b950-221b7511f970"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: https
      port: 443
      targetPort: 9001
    - name: api
      port: 9000
      targetPort: 9000